### ISSUE TITLE
[BUG] ultraschall.RenderProjectRegions_RenderCFG broken

### ISSUE THREAD

**Issue by elzoido** [Ultraschall/ultraschall-lua-api-for-reaper#7]
When trying to use ultraschall.RenderProjectRegions_RenderCFG, the region will not be rendered. This is even in the example script. Presumably, the other RenderProject-functions are also broken in the same way.

If I insert a "ultraschall.ShowLastErrorMessage()" into Scripts_Examples/US_Api_Examples_Render_Region_of_current_Project.lua directly behind the render function call, I get

"param: rendercfg2
error: No valid render_cfg-string"

The root of the problem should be that the new optional rendercfg2-String is not as optional as it should be according to the documentation.

rendercfg2 was introduced in 56e91a88c036912c9e704f326176f9a8f3fad9b3 I presume this bug was introduced then as well.

**What did you expect to happen?**

The region should be rendered as FLAC.

**What happened instead?**

It was not.

**Version of Ultraschall**

LUA-API 4.1.002 (I'm only using the API installed via Reapack)

**REAPER version running Ultraschall**

v6.12c/x64

**Comment by mespotine** [comment]
Thanx, I will check.

**Comment by mespotine** [comment]
Ok, after some first tests it's simply that this function is a deprecated one, as it used the first batch of rendering-functions I made back then, who weren't as good as they should have been. I removed the function from the docs but not from the API to keep old stuff still working and I missed updating the example-scripts because of that.

Having said that, I'll debug the function anyway for backwards compatibility(and I'll update the example-scripts as well).

In the meantime, I suggest you to use this new function instead:
https://mespotin.uber.space/Ultraschall/US_Api_Functions.html#RenderProject_Regions
It's more powerful, versatile and better to code with than the old one. 
The rendercfg2-parameter should be optional without a problem. If not, give me a hint with a code-snippet and an example-project, which shows the bug and I'll fix it asap.

BTW: the current version of Ultraschall-API should be  4.1.003, so it's probably worth updating your ReaPack(I released the new version last week, so you probably missed it yet).

**Comment by mespotine** [comment]
Holy Cow, the whole rendercfg2-management was broken so big big thank you for reporting that so I could fix it. Will upload a fix within the next few hours, including updated example-scripts, who have outdated code for the render-examples as well.

**Comment by mespotine** [comment]
Fixed, just update your ReaPack and it should work now.

**Comment by elzoido** [comment]
Thanks for the quick fix, keep up the good work!

Small thing though, the ReaPack-Repository https://github.com/Ultraschall/ultraschall-lua-api-for-reaper/raw/master/ultraschall_api_index.xml still points to Ultraschall-API-4.1.003 and I think (at least from viewing the source) the bug should be fixed in Ultraschall-API-4.1.004.

**Comment by mespotine** [comment]
That's expected. I've added a mechanism into Ultraschall-API, which allows me to add hotfixes without having to build a completely new release. This makes fixing bugs for me much quicker.
ReaPack notices that I changed something, as I'm changing the buildnumber in the index-file for this and allows you to update it.

**Comment by elzoido** [comment]
Maybe this does not work at the moment?

I'm pretty sure I updated today via ReaPack and this morning there was a new package. But the bug was not fixed there.

Well, I'm not at my Reaper workstation anymore, so I'll try again tomorrow.

**Comment by mespotine** [comment]
You should try the updated example-scripts, as they should work now without a problem.

Don't be confused by the changelog, as the actual bug happened in another function on which RenderProjectRegions relies on, so I fixed it over there.

Will release another fix for a bug reported to me quite soon, so expect another update then ;)

**Comment by elzoido** [comment]
That's really weird.

I see the hotfix file with the correct version of the function, GetApiVersion() is "410.003" and ultraschall.hotfixdate is "10_Jul_2020" but when I run the example or my code, the old function is called (I confirmed this by adding a different error message to the beginning of the function of the hotfix and regular module file).

**Comment by mespotine** [comment]
Hmm, I have no idea why that is(something like that had been reported by someone else too), so I made another hotfix, were I overwrote the original function with the fixed ones. This means more work for me but at least, it should work now.

Could you test and give me a note, if it works now? Oh, and which OS are you using?

**Comment by elzoido** [comment]
First test was successful, thanks!

I'm using Windows 10 (Release 2004).

**Comment by mespotine** [comment]
Ok, I consider this fixed. If not, just reopen it.
